package com.knowledgeflow.audit.enums;

public enum AuditAction {

    // Auth
    USER_LOGIN,

    // Clients
    CLIENT_CREATED,
    CLIENT_UPDATED,
    CLIENT_ARCHIVED,

    // Knowledge Cases
    KNOWLEDGE_CASE_CREATED,
    KNOWLEDGE_CASE_UPDATED,
    KNOWLEDGE_CASE_SUBMITTED_FOR_REVIEW,
    KNOWLEDGE_CASE_CHANGES_REQUESTED,
    KNOWLEDGE_CASE_VALIDATED,
    KNOWLEDGE_CASE_REJECTED,
    KNOWLEDGE_CASE_ARCHIVED,

    // Knowledge Q&A
    KNOWLEDGE_QA_IMPORTED,
    KNOWLEDGE_QA_UPDATED,
    KNOWLEDGE_QA_STATUS_CHANGED,
    KNOWLEDGE_QA_VALIDATED,
    KNOWLEDGE_QA_REJECTED,
    KNOWLEDGE_QA_ARCHIVED,
    KNOWLEDGE_QA_SOURCE_ADDED,
    KNOWLEDGE_QA_PUBLISHED,
    KNOWLEDGE_QA_UNPUBLISHED,
    KNOWLEDGE_QA_VERSION_CREATED,
    KNOWLEDGE_QA_REINDEXED,

    // AT FAQ ingestion pilot
    AT_FAQ_DISCOVERY_STARTED,
    AT_FAQ_DISCOVERY_COMPLETED,
    AT_FAQ_DRY_RUN_COMPLETED,
    AT_FAQ_IMPORT_COMPLETED,
    AT_FAQ_ITEM_NEW,
    AT_FAQ_ITEM_CHANGED,
    AT_FAQ_ITEM_POSSIBLY_REMOVED,
    AT_FAQ_PARSE_FAILED,
    AT_FAQ_SECURITY_BLOCKED,

    // Auth bootstrap
    ADMIN_BOOTSTRAPPED
}
