package com.knowledgeflow.common.error;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,
    CONFLICT,
    INVALID_STATE_TRANSITION,
    EXTERNAL_SERVICE_ERROR,
    AI_PROVIDER_ERROR,
    AI_PROVIDER_TIMEOUT,
    AI_PROVIDER_UNAVAILABLE,
    AI_PROVIDER_INVALID_RESPONSE,
    AI_RATE_LIMIT_ERROR,
    AI_CONFIGURATION_ERROR,
    EMBEDDING_TIMEOUT,
    EMBEDDING_UNAVAILABLE,
    EMBEDDING_INVALID_VECTOR,
    INVALID_REQUEST_BODY,
    INTERNAL_ERROR
}
